### ISSUE TITLE
Error: Call to a member function getFrom()

### ISSUE THREAD

**Issue by zakharov-ilia** [mehdikhody/bot#2]
Hello!

I've just installed yii2 base app and this package and set webook adress to controller in my app.

But, when i try to send a message got this problem:
Call to a member function getFrom() on null in .../vendor/khoram/bot/object/Update.php:65

Controller (from example):
```
public function actionHook()
{
   $bot = new Bot([
      'token' => '111111:AAHfgVNT-BQ9yE9mvxTIvqhdqknqI1yvUIY'
   ]);
   $update = Bot::$update;
   $user = Bot::$user;
   $chat = Bot::$chat;
}
```
What is going wrong?

**Comment by mehdikhody** [comment]
`on null` means `Bot::$update` hasn't set yet, and you can't use `Bot::$user` in your program;
because `$user` getting information from `$update`.

I tested the code and it is working. 
Please attach your codes fully.

**Comment by zakharov-ilia** [comment]
This is whole controller file.
```
<?php

namespace app\controllers;

use Yii;

use bot\Bot;
use bot\object\Error;
use yii\web\Controller;
use yii\web\Response;

class RunbabyrunController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
           
        ];
    }

    
    public function actionHook()
    {
        $bot = new Bot([
      'token' => '111111:AAHfgVNT-BQ9yE9mvxTIvqhdqknqI1yvUIY'
   ]);
   $update = Bot::$update;
   $user = Bot::$user;
   $chat = Bot::$chat;
    }
}

```


Log file:
```
2017-10-22 16:18:46 [149.154.167.232][-][-][error][Error] Error: Call to a member function getFrom() on null in .../vendor/khoram/bot/object/Update.php:65
Stack trace:
#0 .../vendor/khoram/bot/base/Bot.php(434): bot\object\Update->getFrom()
#1 .../vendor/khoram/bot/base/Bot.php(374): bot\base\Bot->setUpdate(Array)
#2 .../vendor/yiisoft/yii2/base/BaseObject.php(108): bot\base\Bot->init()
#3 .../controllers/RunbabyrunController.php(28): yii\base\BaseObject->__construct(Array)
#4 [internal function]: app\controllers\RunbabyrunController->actionHook()
#5 .../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 .../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 .../vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('hook', Array)
#8 .../vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('runbabyrun/hook...', Array)
#9 .../vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 .../web/index.php(12): yii\base\Application->run()
```

**Comment by zakharov-ilia** [comment]
So, the main case is to work only with webhook, with any long processes. I just use the example from wiki "execute on localhost", where i found that action.

**Comment by mehdikhody** [comment]
There is something wrong with telegram's updates.
Add follows lines to your program and send the result in this issue.

```php
$update = file_get_contents('php://input');
$content = print_r($update, true);

file_put_contents(__DIR__ . '/update.log', $content);
```

In your case, `Bot::$update` is null and you can't use its properties.

**Comment by zakharov-ilia** [comment]
2 results: for usual message and "bot command" message (with prefix "/"):
```
{
"update_id":353611111,
"message":
    {
    "message_id":76,
    "from":
        {
        "id":94341111,
        "is_bot":false,
        "first_name":"Ilia",
        "username":"Zakharov_ilia",
        "language_code":"ru-RU"
        },
    "chat":
        {
        "id":94341111,
        "first_name":"Ilia",
        "username":"Zakharov_ilia",
        "type":"private"
        },
    "date":1508708754,
    "text":"/start",
    "entities":
        [{
        "offset":0,
        "length":6,
        "type":"bot_command"
        }]
    }
}
```
```
{
"update_id":353611111,
"message":
    {
    "message_id":76,
    "from":
        {
        "id":94341111,
        "is_bot":false,
        "first_name":"Ilia",
        "username":"Zakharov_ilia",
        "language_code":"ru-RU"
        },
    "chat":
        {
        "id":94341111,
        "first_name":"Ilia",
        "username":"Zakharov_ilia",
        "type":"private"
        },
    "date":1508708754,
    "text":"/start",
    }
}
```

*some personal data was changed.

**Comment by mehdikhody** [comment]
Updates is fine, probably `bot\base\Bot` object has damaged.
go to `bot\base` path and use this command in your command line.

```shall
php -r "copy('https://raw.githubusercontent.com/mehdikhody/bot/v2/base/Bot.php', 'Bot.php');"
```

**Comment by zakharov-ilia** [comment]
You are right. Files from github works fine.

It was very, very strange bug us for me.

Thanks!!
